'use strict';

const FILTER_TYPES = Object.freeze([
  'text',
  'multi',
  'date_range',
  'tag_multi',
]);

const FILTER_OPERATORS = Object.freeze({
  text: Object.freeze(['contains']),
  multi: Object.freeze(['in']),
  date_range: Object.freeze(['between']),
  tag_multi: Object.freeze(['in']),
});

const DISPLAY_MODES = Object.freeze([
  'horizontal',
  'more',
  'date_range',
  'hidden',
]);

const PAGE_REQUIRED_PERMISSIONS = Object.freeze({
  customers: Object.freeze(['view_customers']),
  intake: Object.freeze(['view_intake']),
  lead_flow: Object.freeze(['view_intake']),
  pipeline: Object.freeze(['view_pipeline']),
  alerts: Object.freeze(['view_alerts']),
  insights: Object.freeze(['view_insights']),
  recycle_bin: Object.freeze(['manage_customer_recycle']),
  contacts: Object.freeze(['view_contacts']),
  recon: Object.freeze(['view_recon']),
});

function definition({
  key,
  label,
  type = 'multi',
  operators = FILTER_OPERATORS[type],
  displayMode = 'horizontal',
  sortOrder,
  sensitive = false,
  requiredPermissions = [],
  pages = ['customers', 'pipeline'],
  tagCategory = '',
}) {
  return Object.freeze({
    key,
    label,
    type,
    enabled: true,
    sensitive,
    operators: Object.freeze([...operators]),
    displayMode,
    sortOrder,
    requiredPermissions: Object.freeze([...requiredPermissions]),
    pages: Object.freeze([...pages]),
    tagCategory,
  });
}

const FILTER_DEFINITIONS = Object.freeze([
  definition({
    key: 'search',
    label: '关键词',
    type: 'text',
    displayMode: 'horizontal',
    sortOrder: 10,
    pages: ['customers', 'intake', 'lead_flow', 'pipeline', 'alerts', 'insights',
      'recycle_bin', 'contacts', 'recon'],
  }),
  definition({
    key: 'country', label: '国家 / 地区', sortOrder: 20,
    pages: ['customers', 'intake', 'lead_flow', 'pipeline', 'insights', 'recycle_bin'],
  }),
  definition({
    key: 'owner',
    label: '分配销售',
    sortOrder: 30,
    sensitive: true,
    requiredPermissions: ['view_all_customers'],
    pages: ['customers', 'intake', 'lead_flow', 'pipeline', 'alerts', 'insights'],
  }),
  definition({
    key: 'stage', label: '客户阶段', sortOrder: 40,
    pages: ['customers', 'pipeline', 'alerts', 'insights'],
  }),
  definition({
    key: 'customer_type',
    label: '客户类型字段',
    sortOrder: 50,
    pages: ['customers', 'intake', 'lead_flow', 'pipeline', 'recon'],
  }),
  definition({
    key: 'industry',
    label: '行业',
    displayMode: 'more',
    sortOrder: 60,
    pages: ['customers', 'intake', 'lead_flow', 'pipeline', 'recon'],
  }),
  definition({
    key: 'priority', label: '客户优先级', displayMode: 'more', sortOrder: 70,
    pages: ['customers', 'pipeline', 'alerts', 'insights'],
  }),
  definition({
    key: 'source', label: '客户来源', displayMode: 'more', sortOrder: 80,
    pages: ['customers', 'pipeline'],
  }),
  definition({
    key: 'creator',
    label: '创建人',
    displayMode: 'more',
    sortOrder: 90,
    sensitive: true,
    requiredPermissions: ['view_all_customers'],
    pages: ['customers', 'pipeline'],
  }),
  definition({
    key: 'last_action',
    label: '最近动作',
    displayMode: 'more',
    sortOrder: 100,
    pages: ['customers', 'pipeline'],
  }),
  definition({
    key: 'next_step',
    label: '下一步',
    displayMode: 'more',
    sortOrder: 110,
    pages: ['customers', 'pipeline'],
  }),
  definition({
    key: 'created_at',
    label: '创建日期',
    type: 'date_range',
    displayMode: 'date_range',
    sortOrder: 120,
    pages: ['customers', 'pipeline'],
  }),
  definition({
    key: 'contact_level',
    label: '联系人等级',
    sortOrder: 20,
    sensitive: true,
    requiredPermissions: ['view_contacts'],
    pages: ['intake', 'lead_flow', 'contacts'],
  }),
  definition({
    key: 'department',
    label: '部门',
    displayMode: 'more',
    sortOrder: 30,
    sensitive: true,
    requiredPermissions: ['view_contacts'],
    pages: ['contacts'],
  }),
  definition({
    key: 'sales_ready',
    label: '交付状态',
    displayMode: 'more',
    sortOrder: 40,
    sensitive: true,
    requiredPermissions: ['view_contacts'],
    pages: ['contacts'],
  }),
  definition({
    key: 'current_pool',
    label: '当前分组',
    displayMode: 'more',
    sortOrder: 40,
    pages: ['recon'],
  }),
  definition({
    key: 'score',
    label: 'Recon 评分',
    displayMode: 'more',
    sortOrder: 50,
    pages: ['recon'],
  }),
  definition({
    key: 'updated_at',
    label: '更新时间',
    type: 'date_range',
    displayMode: 'date_range',
    sortOrder: 60,
    pages: ['intake', 'lead_flow', 'contacts', 'recon'],
  }),
  definition({
    key: 'status',
    label: '线索状态',
    displayMode: 'horizontal',
    sortOrder: 42,
    pages: ['intake', 'lead_flow'],
  }),
  definition({
    key: 'source_batch',
    label: '来源批次',
    displayMode: 'more',
    sortOrder: 82,
    pages: ['intake', 'lead_flow'],
  }),
  definition({
    key: 'has_website',
    label: '官网',
    displayMode: 'more',
    sortOrder: 92,
    pages: ['intake', 'lead_flow'],
  }),
  definition({
    key: 'has_named_contact',
    label: '具名联系人',
    displayMode: 'more',
    sortOrder: 94,
    sensitive: true,
    requiredPermissions: ['view_contacts'],
    pages: ['intake', 'lead_flow'],
  }),
  definition({
    key: 'unassigned_only',
    label: '仅未分配',
    displayMode: 'more',
    sortOrder: 96,
    pages: ['intake'],
  }),
  definition({
    key: 'urgency',
    label: '紧急程度',
    sortOrder: 45,
    pages: ['alerts'],
  }),
  definition({
    key: 'due_status',
    label: '计划状态',
    displayMode: 'more',
    sortOrder: 55,
    pages: ['alerts'],
  }),
  definition({
    key: 'due_at',
    label: '计划日期',
    type: 'date_range',
    displayMode: 'date_range',
    sortOrder: 65,
    pages: ['alerts'],
  }),
  definition({
    key: 'evaluation_status',
    label: '评价覆盖',
    sortOrder: 45,
    pages: ['insights'],
  }),
  definition({
    key: 'evaluation_author',
    label: '评价人',
    displayMode: 'more',
    sortOrder: 55,
    sensitive: true,
    requiredPermissions: ['view_insights'],
    pages: ['insights'],
  }),
  definition({
    key: 'evaluation_updated_at',
    label: '评价日期',
    type: 'date_range',
    displayMode: 'date_range',
    sortOrder: 65,
    sensitive: true,
    requiredPermissions: ['view_insights'],
    pages: ['insights'],
  }),
  definition({
    key: 'recycle_kind',
    label: '回收类型',
    sortOrder: 40,
    pages: ['recycle_bin'],
  }),
  definition({
    key: 'previous_owner',
    label: '原负责人',
    displayMode: 'more',
    sortOrder: 50,
    sensitive: true,
    requiredPermissions: ['view_all_customers'],
    pages: ['recycle_bin'],
  }),
  definition({
    key: 'recycled_at',
    label: '回收日期',
    type: 'date_range',
    displayMode: 'date_range',
    sortOrder: 60,
    pages: ['recycle_bin'],
  }),
  definition({
    key: 'tag_customer_type',
    label: '客户类型',
    type: 'tag_multi',
    sortOrder: 200,
    tagCategory: '客户类型',
    pages: ['customers', 'intake', 'lead_flow', 'pipeline'],
  }),
  definition({
    key: 'tag_business_product',
    label: '客户经营产品',
    type: 'tag_multi',
    sortOrder: 210,
    sensitive: true,
    requiredPermissions: ['view_contacts'],
    tagCategory: '客户经营产品',
    pages: ['customers', 'intake', 'lead_flow', 'pipeline'],
  }),
  definition({
    key: 'tag_demand_product',
    label: '需求 / 采购产品',
    type: 'tag_multi',
    sortOrder: 220,
    sensitive: true,
    requiredPermissions: ['view_contacts'],
    tagCategory: '需求/采购产品',
    pages: ['customers', 'intake', 'lead_flow', 'pipeline'],
  }),
  definition({
    key: 'tag_industry',
    label: '应用行业',
    type: 'tag_multi',
    sortOrder: 230,
    tagCategory: '应用行业',
    pages: ['customers', 'intake', 'lead_flow', 'pipeline'],
  }),
  definition({
    key: 'tag_focus_scenario',
    label: '重点场景',
    type: 'tag_multi',
    sortOrder: 240,
    tagCategory: '重点场景',
    pages: ['customers', 'intake', 'lead_flow', 'pipeline'],
  }),
  definition({
    key: 'tag_needs_confirmation',
    label: '需确认属性',
    type: 'tag_multi',
    sortOrder: 250,
    sensitive: true,
    tagCategory: '需确认属性',
    pages: ['customers', 'intake', 'lead_flow', 'pipeline'],
  }),
  definition({
    key: 'tag_list',
    label: '名单标签',
    type: 'tag_multi',
    sortOrder: 260,
    sensitive: true,
    tagCategory: '名单标签',
    pages: ['customers', 'intake', 'lead_flow', 'pipeline'],
  }),
]);

function sourceFromDefinition(item) {
  return Object.freeze({
    key: item.key,
    label: item.label,
    type: item.type,
    operators: Object.freeze([...item.operators]),
    displayMode: item.displayMode,
    sortOrder: item.sortOrder,
    sensitive: item.sensitive,
    requiredPermissions: Object.freeze([...item.requiredPermissions]),
    pages: Object.freeze([...item.pages]),
    tagCategory: item.tagCategory,
  });
}

// Sources are server-owned query adapters. Administrators can create definitions
// only for sources in this catalog; the database never supplies SQL or column names.
const FILTER_SOURCE_CATALOG = Object.freeze([
  ...FILTER_DEFINITIONS.map(sourceFromDefinition),
  sourceFromDefinition(definition({
    key: 'city',
    label: '城市',
    displayMode: 'more',
    sortOrder: 25,
    pages: ['customers'],
  })),
]);

module.exports = {
  FILTER_TYPES,
  FILTER_OPERATORS,
  DISPLAY_MODES,
  PAGE_REQUIRED_PERMISSIONS,
  FILTER_DEFINITIONS,
  FILTER_SOURCE_CATALOG,
};
